CREATE TABLE dt_questions
(
  question_text VARCHAR(50) NULL,
  url VARCHAR(100) NULL,
  answer VARCHAR(50) NOT NULL,
  user_id VARCHAR(25) NOT NULL,
  state TINYINT UNSIGNED NOT NULL,
  question_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
